---
abstract: 'runtime module handling'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Runtime
provides:
  Module::Runtime:
    file: lib/Module/Runtime.pm
    version: 0.014
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.fysh.org/zefram/Module-Runtime.git
version: 0.014
